/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    FullscreenLoader: typeof import('./src/components/layout/FullscreenLoader.vue')['default']
    InputText: typeof import('./src/components/input/InputText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavigation: typeof import('./src/components/layout/SideNavigation.vue')['default']
    TestSidebar: typeof import('./src/components/layout/TestSidebar.vue')['default']
    UApp: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBadge: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UButtonGroup: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/ButtonGroup.vue')['default']
    UCard: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDashboardGroup: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/DashboardGroup.vue')['default']
    UDashboardPanel: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/DashboardPanel.vue')['default']
    UDashboardResizeHandle: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/DashboardResizeHandle.vue')['default']
    UDashboardSidebar: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/DashboardSidebar.vue')['default']
    UDashboardSidebarToggle: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/DashboardSidebarToggle.vue')['default']
    UForm: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UKbd: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Kbd.vue')['default']
    ULink: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    ULinkBase: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/LinkBase.vue')['default']
    UModal: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/Page.vue')['default']
    UPageAside: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/PageAside.vue')['default']
    UPageBody: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/PageBody.vue')['default']
    UPageCard: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/PageCard.vue')['default']
    UPageHeader: typeof import('./../../node_modules/@nuxt/ui-pro/dist/runtime/components/PageHeader.vue')['default']
    USelectMenu: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USeparator: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USkeleton: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    USwitch: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTabs: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./../../node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
